version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '4000:4000'
    volumes:
      - ./UniAlugue-API/

  db:
    image: mysql:5.7
    volumes:
      - ./UniAlugue-API/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: banco_unialugue
      MYSQL_PASSWORD: password
